server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/application-config
eureka:
  client:
    region: default
    registerFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/  

security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM